install.packages(shinydashboard)
install.packages(shiny)
install.packages(leaflet)
install.packages(maptools)
install.packages(raster)
install.packages(osmdata)
install.packages(fmsb)
install.packages(rgdal)